[package]
name = "axum_crud"
version = "0.1.0"
edition = "2024"

[dependencies]
# --- Web / HTTP ---
axum = "0.8.4"

# --- Async runtime ---
tokio = { version = "1.47.1", features = ["full"] }

# --- Serde / JSON ---
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.142"

# --- Time / Random number / ---
chrono = { version = "0.4", features = ["serde", "clock"] }
rand = "0.9"

# --- Database / Cache ---
sqlx = { version = "0.8.6", features = ["runtime-tokio", "tls-rustls","macros" ,"postgres", "chrono", "json"] }

# --- Error handling ---
anyhow = "1.0"

# ğŸ” Environment konfiguratsiyasi
dotenvy = "0.15.7"

# ğŸ“‹ Logging
tracing = "0.1.40"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
